FROM node:18

ARG DD_API_KEY

ENV DD_API_KEY=$DD_API_KEY \
    DD_AGENT_MAJOR_VERSION=7 \
    DD_APM_ENABLED=true \
    DD_HOSTNAME="shark-dd-trace-gcp" \
    DD_SITE="us5.datadoghq.com" \
    DD_APM_NON_LOCAL_TRAFFIC=true \
    DD_ENV="dev" \
    DD_VERSION="1.0.0" \
    DD_SERVICE="shark-dd-trace-gcp" \
    DD_PROFILING_ENABLED=true \
    DD_LOGS_INJECTION=true \
    DD_APPSEC_ENABLED=true \
    DD_IAST_ENABLED=true \
    DD_APPSEC_SCA_ENABLED=true

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN apt-get update && \
    apt-get install -y ca-certificates

COPY . .

COPY --from=datadog/serverless-init:1 /datadog-init /app/datadog-init

EXPOSE 80

CMD [ "/app/datadog-init", "node", "app.js" ]